[package]
name = "timer_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28"
clap = { version = "4.1", features = ["derive"] }
humantime = "2.1"
rodio = "0.17"
native-dialog = "0.7.0"
daemonize = "0.4"
chrono = "0.4"
libc = "0.2"
